// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class audit_log
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    public string user_id { get; set; }
    [ForeignKey("user_id")]
    public virtual ApplicationUser User { get; set; }

    [StringLength(255)]
    public string action { get; set; }

    [StringLength(255)]
    public string entity_type { get; set; }

    [StringLength(255)]
    public string entity_id { get; set; }

    public string old_values { get; set; }

    public string new_values { get; set; }

    [StringLength(255)]
    public string ip_address { get; set; }

    [StringLength(255)]
    public string user_agent { get; set; }

    public DateTime? timestamp { get; set; } = DateTime.UtcNow;
}