// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class cart_item
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string cart_id { get; set; }
    [ForeignKey("cart_id")]
    public virtual shopping_cart Cart { get; set; }

    [StringLength(255)]
    public string product_id { get; set; }
    [ForeignKey("product_id")]
    public virtual product Product { get; set; }

    public int? quantity { get; set; } = 1;
    public string? size { get; set; }
    public string? color { get; set; }

    public DateTime? added_at { get; set; } =DateTime.Now;
}