// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class category
{
    [Key]
    [StringLength(450)]
    public string id { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public string description { get; set; }

    [StringLength(255)]
    public string image_url { get; set; }

    [StringLength(450)]
    public string parent_category_id { get; set; }
    [ForeignKey("parent_category_id")]
    public virtual category ParentCategory { get; set; }

    public string created_by { get; set; }
    [ForeignKey("created_by")]
    public virtual ApplicationUser CreatedByUser { get; set; }

    public DateTime? created_at { get; set; } = DateTime.UtcNow;


    public string last_modified_by { get; set; }
    [ForeignKey("last_modified_by")]
    public virtual ApplicationUser LastModifiedByUser { get; set; }

    public DateTime? last_modified_at { get; set; } = DateTime.UtcNow;

    public bool? is_active { get; set; } = true;
    public bool is_deleted { get; set; } = false;

    public string deleted_by { get; set; }
    [ForeignKey("deleted_by")]
    public virtual ApplicationUser DeletedByUser { get; set; }
}