// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class chat_session
{
    [Key]
    [StringLength(255)]
    public string Id { get; set; }
    public string CustomerId { get; set; }
    public string SellerId { get; set; }

    [ForeignKey("CustomerId")]
    public virtual ApplicationUser Customer { get; set; }

    [ForeignKey("SellerId")]
    public virtual ApplicationUser Seller { get; set; }

    public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? LastMessageAt { get; set; } = DateTime.UtcNow;
    public string Status { get; set; }
    public DateTime? ClosedAt { get; set; }
    public bool IsDeleted { get; set; } = false;

    // Navigation property for chat messages
    public virtual ICollection<chat_message> ChatMessages { get; set; }
}