// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class chat_message
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string session_id { get; set; }

    public string sender_id { get; set; }

    [ForeignKey("sender_id")]
    public virtual ApplicationUser Sender { get; set; }

    public string message { get; set; }

    public DateTime? sent_at { get; set; } = DateTime.UtcNow;

    public bool? is_read { get; set; }
    public bool? is_deleted { get; set; } = false;

}