// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class discount
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    public string description { get; set; }

    [StringLength(255)]
    public string discount_type { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? value { get; set; }

    public DateTime? start_date { get; set; } = DateTime.UtcNow;

    public DateTime? end_date { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? minimum_order_amount { get; set; }

    public int? max_uses { get; set; }

    public int? current_uses { get; set; }

    public bool is_active { get; set; }
    public bool is_deleted { get; set; } = false;
    public string seller_id { get; set; }
    [ForeignKey("seller_id")]
    public virtual ApplicationUser Seller { get; set; }

    public DateTime? created_at { get; set; } = DateTime.UtcNow;
    public virtual ICollection<product_discount> ProductDiscounts { get; set; }
}