// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class notification
{
    [Key]
    [StringLength(255)]
    public string Id { get; set; }

    [StringLength(450)]
    public string RecipientId { get; set; }
    [ForeignKey("RecipientId")]
    public virtual ApplicationUser Recipient { get; set; }

    [StringLength(255)]
    public string Title { get; set; }

    public string Message { get; set; }

    [StringLength(50)]
    public string Type { get; set; } // "Order", "Review", "Chat", "Stock", "Discount"

    [StringLength(255)]
    public string RelatedEntityId { get; set; } // ID of related entity (order_id, review_id, etc.)

    public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;

    public bool IsRead { get; set; } = false;

    public bool IsDeleted { get; set; } = false;

    public DateTime? ReadAt { get; set; }

    public string OrderId { get; set; }
} 