// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class order_item
{
    [Key]
    public string id { get; set; }
    public string order_id { get; set; }
    [ForeignKey("order_id")]
    public virtual order order { get; set; }

    public string seller_id { get; set; }

    [ForeignKey("seller_id")]
    public virtual ApplicationUser Seller { get; set; }

    public string product_id { get; set; }
    [ForeignKey("product_id")]
    public virtual product product { get; set; }

    public int? quantity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? unit_price { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? discount_applied { get; set; }
    [Column(TypeName = "nvarchar(32)")]
    public string status { get; set; }
    public string Color{ get; set; }
    public string Size{ get; set; }
}