// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class order
{
    [Key]
    public string id { get; set; }
    public string buyer_id { get; set; }

    [ForeignKey("buyer_id")]
    public virtual ApplicationUser Buyer { get; set; }

    public virtual ICollection<order_item> OrderItems { get; set; } = new List<order_item>();

    public DateTime? order_date { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? total_amount { get; set; }

    public string shipping_address { get; set; }

    public string billing_address { get; set; }

    [StringLength(255)]
    public string status { get; set; }

    [StringLength(255)]
    public string payment_method { get; set; }

    [StringLength(255)]
    public string payment_status { get; set; }

    [StringLength(255)]
    public string tracking_number { get; set; }

    public DateOnly? estimated_delivery_date { get; set; }

    public DateTime? delivered_at { get; set; }
    public bool is_deleted { get; set; } = false;

}