// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class product_review
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string product_id { get; set; }
    [ForeignKey("product_id")]
    public virtual product product { get; set; }
    
    public string user_id { get; set; }
    [ForeignKey("user_id")]
    public virtual ApplicationUser User { get; set; }

    public int? rating { get; set; }

    [StringLength(255)]
    public string title { get; set; }

    public string comment { get; set; }

    public DateTime? created_at { get; set; } = DateTime.UtcNow;

    public bool? is_verified_purchase { get; set; }

    // Navigation property for replies
    public virtual ICollection<review_reply> replies { get; set; }
}