// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class product_image
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string product_id { get; set; }
    [ForeignKey("product_id")]
    public virtual product product { get; set; }

    [StringLength(255)]
    public string image_url { get; set; }
    public string image_type { get; set; } = "sub"; // "main" or "sub"


    public bool? is_primary { get; set; }

    public DateTime? uploaded_at { get; set; }
}