// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class review_reply
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string review_id { get; set; }
    [ForeignKey("review_id")]
    public virtual product_review review { get; set; }

    [StringLength(450)]
    public string replier_id { get; set; }
    [ForeignKey("replier_id")]
    public virtual ApplicationUser Replier { get; set; }

    public string reply_text { get; set; }

    public DateTime? created_at { get; set; } = DateTime.UtcNow;

    public bool? is_seller_reply { get; set; } = true; // true for seller, false for customer

    public bool? is_deleted { get; set; } = false;
} 