// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class shopping_cart
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }


    public string user_id { get; set; }
    [ForeignKey("user_id")]
    public virtual ApplicationUser User { get; set; }

    public DateTime? created_at { get; set; }=DateTime.UtcNow;

    public DateTime? last_updated_at { get; set; } = DateTime.UtcNow;

    public virtual ICollection<cart_item> CartItems { get; set; }

}