// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

public partial class support_ticket
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }
    public string user_id { get; set; }

    [ForeignKey("user_id")]
    public virtual ApplicationUser User { get; set; }

    [StringLength(255)]
    public string subject { get; set; }

    public string description { get; set; }

    [StringLength(255)]
    public string status { get; set; }

    [StringLength(255)]
    public string priority { get; set; }

    public DateTime? created_at { get; set; } = DateTime.UtcNow;

    public DateTime? resolved_at { get; set; }

    [StringLength(255)]
    public string resolved_by { get; set; }
    public bool is_deleted { get; set; } = false;

}