// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Final_project.Models;

[Table("ticket_history")]
public partial class ticket_history
{
    [Key]
    [StringLength(255)]
    public string id { get; set; }

    [StringLength(255)]
    public string ticket_id { get; set; }
    [ForeignKey("ticket_id")]
    public virtual support_ticket Support_Ticket { get; set; }      

    [StringLength(255)]
    public string changed_by { get; set; }

    public DateTime? changed_at { get; set; }

    [StringLength(255)]
    public string field_changed { get; set; }

    public string old_value { get; set; }

    public string new_value { get; set; }
}